Add docstring to ovn_unconfigure function
This patch adds documentation to the ovn_unconfigure
function.
This is needed because the lack of doc triggers
an exception when using the command 'vdsm-tool' help

 ovn-unconfigure
Traceback (most recent call last):
  File "/usr/bin/vdsm-tool", line 234, in <module>
    sys.exit(main())
  File "/usr/bin/vdsm-tool", line 216, in main
    usage_and_exit(1)
  File "/usr/bin/vdsm-tool", line 153, in usage_and_exit
    _usage_module(mod_name, mod_desc)
  File "/usr/bin/vdsm-tool", line 132, in _usage_module
    _usage_command(cmd_name, cmd_docs)
  File "/usr/bin/vdsm-tool", line 125, in _usage_command
    print_command_usage(tool_command[cmd_name]["command"])
  File "/usr/bin/vdsm-tool", line 120, in print_command_usage
    cmd.__doc__.lstrip(), file=stream)
AttributeError: 'NoneType' object has no attribute 'lstrip'

Change-Id: Ia8d382f971b52c538ca0cfc2028437c47970d4ba
Signed-off-by: MosheSheena <msheena@redhat.com>